### ISSUE TITLE
Jersey 2 Compatibility

### ISSUE THREAD

**Issue by bowenwr** [bazaarvoice/jersey-hmac-auth#47]
It looks like this project is only compatible with Jersey 1. Even adding it to my POM for Jersey 2.19 without adding any other classes causes an error, even when I exclude Jersey 1:

```
javax.servlet.ServletException: Servlet.init() for servlet com.test.api.Application threw exception
	org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:100)
	org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:953)
	org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
	org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1041)
	org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:603)
	org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:310)
	java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	java.lang.Thread.run(Thread.java:744)
root cause

java.lang.IllegalStateException: The resource configuration is not modifiable in this context.
	org.glassfish.jersey.server.ResourceConfig$ImmutableState.register(ResourceConfig.java:273)
	org.glassfish.jersey.server.ResourceConfig$ImmutableState.register(ResourceConfig.java:220)
	org.glassfish.jersey.server.ResourceConfig.register(ResourceConfig.java:452)
	org.glassfish.jersey.servlet.WebComponent.<init>(WebComponent.java:334)
	org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:170)
	org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:362)
	javax.servlet.GenericServlet.init(GenericServlet.java:160)
	org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:100)
	org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:953)
	org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
	org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1041)
	org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:603)
	org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:310)
	java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	java.lang.Thread.run(Thread.java:744)
```

I can see in the source it's referencing the old com.sun packages.

Any plans to support Jersey 2? It will probably be late for me (HMAC integration due tomorrow) but might be nice for progeny.

**Comment by keyboardsamurai** [comment]
Seconded. I am using it with Dropwizard 0.8.x at the moment. And after removing the dependencies to jersey 1.x it becomes apparent, that there is no way around a refactoring of the core packages.

**Comment by bentonporter** [comment]
This is a known constraint:  https://github.com/bazaarvoice/jersey-hmac-auth/wiki/FAQ.  Perhaps it is something that can be added in a future release.  (Also, I'd be happy to contribute this, but I can't guarantee when it will be ready and available.)

**Comment by l0s** [comment]
Hi all, I have an implementation that partially works, but I am not too familiar with extending Jersey 2. There is currently an issue with the resource methods being invoked twice for each request, the first time without the injected principal and the second time with. Maybe someone more familiar with Jersey 2 can point me in the right direction?

**Comment by l0s** [comment]
I have an open pull request to add Jersey 2 compatibility: https://github.com/bazaarvoice/jersey-hmac-auth/pull/48 . If anyone has any feedback on it, I would be happy to make changes. This is something that would be very useful for my team.

**Comment by joeslice** [comment]
@bowenwr I believe this issue can be closed with the recent release.  Can you please confirm and reopen if you think there is still an issue?

Thanks!
