### ISSUE TITLE
Misuses of cryptographic APIs

### ISSUE THREAD

**Issue by mhp0rtal** [bazaarvoice/jersey-hmac-auth#69]
Hi
The following lines have cryptographic API misuses. <br> File name => common/src/main/java/com/bazaarvoice/auth/hmac/common/Signer.java: Line number => 29: API name => SecretKeySpec:<BR> File name => common/src/main/java/com/bazaarvoice/auth/hmac/common/Signer.java: Line number => 29: API name => SecretKeySpec:<BR>

**Comment by joeslice** [comment]
Closing as spam.
